version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
     - bridge-network

  shareloc.server.app:
    depends_on:
     - dynamodb-local
    image: ${DOCKER_REGISTRY-}sharelocserverapp
    container_name: shareloc-server
    ports:
     - "5113:5113"
     - "7058:7058"
    build:
      context: .
      dockerfile: Server/ShareLoc.Server.App/Dockerfile
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
